packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
  - lightningcss
  - workerd

allowBuilds:
  esbuild: true
  '@tailwindcss/oxide': true
  lightningcss: true
  workerd: true
